### ISSUE TITLE
deriveEth2ValidatorKeys signing key derivation path

### ISSUE THREAD

**Issue by imnisen** [ChainSafe/bls-keygen#15]
https://github.com/ChainSafe/bls-keygen/blob/32b06822b490ee679f7e1334858b8ec5beac5cf1/src/index.ts#L64

Hi, when deriving eth2 validator keys, why the signing key derived from path `m/12381/3600/${validatorIndex}/0/0` not `m/12381/3600/${validatorIndex}/1`, as eip-2334 specify `m / purpose / coin_type /  account / use` format.

**Comment by wemeetagain** [comment]
Hey @imnisen,
EIP 2334 has a brief section on "Eth2-specific parameters", check out https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2334.md#eth2-specific-parameters

I can definitely see this more eth2-specific functionality spinning into its own repo at some point, however for the sake of completeness in implementing the EIP, we included it here for now.

**Comment by imnisen** [comment]
Thanks! I missed the "Eth2-specific parameters" section. That makes sense now. ;)
