### ISSUE TITLE
bcrypto with bn.js 

### ISSUE THREAD

**Issue by tynes** [ChainSafe/bls-keygen#3]
`bcrypto` has an extended `bn.js` included in it with lots of new cryptographic operations. This would allow you do drop `bn.js` as a dependency. Note that the author of bn.js is the original author of `bcoin`.

https://github.com/indutny/bn.js
https://github.com/bcoin-org/bcoin/blob/master/package.json#L11
https://github.com/bcoin-org/bcrypto/blob/master/lib/js/bn.js

**Comment by mpetrunic** [comment]
Hey there, tnx for info. Any chance bcrypto will include typescript definitions?

It's extremely difficult to use it in typescript project such as this (either make compiler ignore it or write own definitions for stuff you use).

**Comment by tynes** [comment]
I think that it is currently unlikely that bcrypto will include typescript definitions as we do not currently use typescript. There has been some talk about adopting typescript after deno is stable, as it natively supports typescript. Making the tsc compiler ignore bcrypto or writing your own definitions doesn't seem like it would be incredibly difficult, I'd be happy to help with any questions if you had them.

**Comment by wemeetagain** [comment]
closing since we no longer use bn js
